language: python
dist: xenial
sudo: true
python:
  - "3.8.7"
env:
  global:
    - DATABASE_URL="sqlite:///:memory"
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v13
  - nvm use v13
  - npm --version
  - npm install -g yarn
  - yarn --version
  - npm install -g gulp-cli
  - yarn install --production
  - gulp --version
  - gulp build --production
  - yarn install
  - gulp build
  - pip install -U pip
  - pip install -U setuptools wheel
  - pip install -r requirements/local.txt
  - pip install coveralls
  - python manage.py collectstatic --no-input
  - python manage.py migrate --no-input
  - gem install coveralls-lcov
script:
  - coverage run manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls-lcov -v -n ./coverage/lcov.info > coverage.json
  - "coveralls --merge=coverage.json"
  - yarn outdated
  - pip list -o
